mongodb:
  # Uncomment below sections when deploying devMode on AKS
  # securityContext:
  #   enabled: true
  #   fsGroup: 63400
  #   runAsUser: 63400
  #persistence:
  #  enabled: true
  #  accessMode: ReadWriteMany
  ####### MongoDB Atlas
  # uri: "mongodb+srv://qseok:c4hoW8GQRPTBQbEF@qlikdb-wn7on.gcp.mongodb.net/qsefe?retryWrites=true&w=majority"
  ####### LocalLAN Container 
  # uri: "mongodb://192.168.2.5:27017/qsefe?ssl=false"
  # uriWebIntegrations: "mongodb://192.168.2.5:27017/qsefe?ssl=false"
  ####### Internal Cluster MongoDB ReplicaSet
  uri: "mongodb://qsefe:qsefe@mongodb-arbiter-0.mongodb-headless.mongodb:27017,mongodb-primary-0.mongodb-headless.mongodb:27017,mongodb-secondary-0.mongodb-headless.mongodb:27017/qsefe?replicaSet=rs0&ssl=false"
  ####### Security
  # usePassword: false
  uriSecretName: "qseok-mongoconfig"
  ssl: true
  sslValidate: false
  checkServerIdentity: false


audit:
  config:
    archive:
      ## Toogle to enable archiving
      enabled: true
      ## Repeat interval for validating and archiving the data
      interval: 1h
    ## S3 configuration for the long term storage archiving
    ##
    storage:
      ## Endpoint to storage provider
      endpoint: "https://s3.us-east-1.amazonaws.com"
      ## Toogle to use secured connection
      ssl: true
      ## Storage access key ID. This is a dummy default value set by MinIO chart
      keyID: AKIAXQXNQARXFR3JS5U3
      ## Storage secret access key. This is a dummy default secret set by MinIO chart
      secretKey: BieS74yYSGQrGOL22Yuj+maYb8OoJwUZGSpF65lQ
      ## Bucket region
      region: us-east-1
      ## Bucket to be used for audits archive
      bucket: qseok-audits
    # minio:
    #   ## Set minio.enabled to true for localdev
    #   enabled: true
    #   ## Default minio port
    #   service:
    #     port: 9000
    #   ## Default bucket creation
    #   ##
    #   defaultBucket:
    #     ## Should be created when the chart is deployed
    #     enabled: true
    #     ## Default bucket name
    #     name: audits
    #   nodeSelector:
    #     kubernetes.io/hostname: "k8s-nfs"
    #   tolerations:
    #   - effect: NoSchedule
    #     operator: Exists

engine:
  acceptEULA: "yes"
  groups:
    enabled: true
  featureflags:
    enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10240m
      nginx.org/client-max-body-size: 10240m
  # replicaCount: 1
  # Defines the persistence layer of the engine - ReadWriteMany is required for multiple engines
  # persistence: 
  #   enabled: true
  #   autoSave:
  #     enabled: true
  #     interval: 5
  #   accessMode: ReadWriteMany
  #   size: 5Gi
  # logging:
  #   HttpTrafficLogVerbosity: 6
  #   TrafficLogVerbosity: 0
  #   SystemLogVerbosity: 6
  #   AuditLogVerbosity: 0
  #   PerformanceLogVerbosity: 0
  #   QixPerformanceLogVerbosity: 0
  #   SessionLogVerbosity: 4
  #   SmartSearchQueryLogVerbosity: 3
  #   SmartSearchIndexLogVerbosity: 3
  #   ScriptLogVerbosity: 4
  #   SSEVerbosity: 4
  #   ExternalServicesLogVerbosity: 4
  #   EnableDebugTracing: false

# elastic-infra:
#   ingress:
#     host: "qseok.browntown.local"
#     class: "nginx"
#     tls:
#       - secretName: jprdonnelly-ssl
#         hosts:
#           - "qseok.browntown.local"
#     annotations:
#       - nginx.ingress.kubernetes.io/proxy-body-size: 10240m
#       - nginx.org/client-max-body-size: 10240m
#   nginx-ingress:
#     controller:
#       extraArgs:
#         default-ssl-certificate: qlik/jprdonnelly-ssl
  #     service:
  #       annotations:
  #         service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
  #         # https://gowalker.org/k8s.io/kubernetes/pkg/cloudprovider/providers/azure#_constants
  #         service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '3600'

collections:
  hpa:
    ## Toggle horizontal pod autoscaler
    enabled: enable
    ## Minimum number of replicas
    minReplicas: 3
    ## Maximum number of replicas
    maxReplicas: 6
    ## See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details
    targetAverageUtilizationCpu: 80
    targetAverageUtilizationMemory: 80

identity-providers:
  secrets:
    idpConfigs:
      - discoveryUrl: "https://djx.auth0.com/.well-known/openid-configuration"
        postLogoutRedirectUri: "https://help.qlik.com"
        clientId: "9kohQL0166VN7RcEv7P7li0gWPBjbiZO"
        clientSecret: "NLwAqaeyGr38xl19Xb9lBXjt5ra1U-_5LKuFwxBnzvSsqmAUXaT6T7BeQGgIRYOd"
        # clockToleranceSec: 5
        realm: "Auth0"
        hostname: "elastic.local"
        # scope: "openid"
        primary: true
        useClaimsFromIdToken: true
        # claimsMapping:
        #   client_id: "user_id"
          # name: "name"

global:
  persistence:
    storageClass: "nfs-client"
  imageRegistry: "jprdonnelly.com:5000/qlik-docker-qsefe.bintray.io"
  #imagePullSecrets:
  #- name: regcred

#### If using an internal registry, uncomment the sections below (prometheus-nats-exporter isn't honoring global.imageRegistry)
messaging:
  nats:
    metrics:
      enabled: false
      image:
        pullPolicy: Never
  nats-streaming:
    metrics:
      enabled: false
      image:
        pullPolicy: Never

# licenses:
# ## Proxy configuration
# ## Set the following values when deploying behind a proxy
#   proxy:
#   ## The URI to the tunneling proxy scheme://host:port (e.g. http://proxy.company.com:8888)
#     uri:

featureflags:
  logLevel: "verbose"
  configmaps:
    create: true
    featureFlagsConfig:
      {
        "globalFeatures": {
          "HUB_MANAGED_SPACES": true,
          "HOME_HOME": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_EDIT_ENABLED": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_MANAGED_SPACES_ENABLED": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_SORT_FILTER_ENABLED": true,
          "HUB_GROUPS": true,
          "createIdpGroups": true,
          "includeGroupIdsInUserJwt": true,
          "excludeGroupsFromJwt": true,
          "MANAGEMENT_CONSOLE_GROUPS_ENABLED": true,
          "sfdc": true,
          "enableCsrf": true,
          "apiClientsEnabled": true,
          "AUDIT_ARCHIVE_ENABLED": true
        },
        "tenantFeatures": {},
        "userFeatures": {}
      }
