apiVersion: v1
kind: PersistentVolume
metadata:
  name: qsefevol
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /qsefevol
    server: <IP From Your Filestore Instance>
