devMode:
  enabled: true
engine:
  acceptEULA: "yes"
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    existingClaim: qsefe-vol
  mira:
   rbac:
       create: true
   serviceAccount:
       create: true
elastic-infra:
   traefik:
       rbac:
           enabled: true
   nginx-ingress:
       rbac:
            create: true
edge-auth:
  secrets:
    idpConfigs:
      - discoveryUrl: "https://djx.auth0.com"
        clientId: "9kohQL0166VN7RcEv7P7li0gWPBjbiZO"
        clientSecret : "NLwAqaeyGr38xl19Xb9lBXjt5ra1U-_5LKuFwxBnzvSsqmAUXaT6T7BeQGgIRYOd"
        realm: "Auth0"
        hostname: "192.168.205.90"