devMode:
  enabled: true

#mongodb:
#  uri: "mongodb://qlik:Qlik1234@10.48.10.76:27017/qsefe?ssl=false"
  # persistence:
  #   enabled: true
  #   accessMode: ReadWriteMany
  #   storageClass: "azurefile"
  # # Set the ID/GID MongoDB will use to access the PV.  This user/group matches the custom setting 
  # # used for qix-datafiles to use azurefile as well.
  # securityContext:
  #   enable: true
  #   fsGroup: 63400
  #   runAsUser: 63400

engine:
  acceptEULA: "yes"
  featureflags:
    enabled: true

elastic-infra:
  nginx-ingress:
    controller:
      # extraArgs:
      #   default-ssl-certificate: default/<name>
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '3600'

identity-providers:
  secrets:
    idpConfigs:
      - discoveryUrl: "https://<TENANT>.auth0.com/.well-known/openid-configuration"
        postLogoutRedirectUri: "https://help.qlik.com"
        clientId: "<CLIENT_ID>"
        clientSecret : "<CLIENT_SECRET>"
        realm: "Auth0"
        hostname: "elastic.local"
        # scope: "openid"
        # primary: true
        useClaimsFromIdToken: true
        # claimsMapping:
          # client_id: "user_id"
          # name: "name"

global:
  persistence:
    storageClass: "azurefile"
    imageRegistry: ""

featureflags:
  configmaps:
    create: true
    featureFlagsConfig:
      {  
        "globalFeatures": {
          "HUB_MANAGED_SPACES": true,
          "HOME_HOME": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_EDIT_ENABLED": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_MANAGED_SPACES_ENABLED": true,
          "MANAGEMENT_CONSOLE_SPACE_MANAGEMENT_SORT_FILTER_ENABLED": true,
          "HUB_GROUPS": true,
          "createIdpGroups": true,
          "includeGroupIdsInUserJwt": true,
          "excludeGroupsFromJwt": true,
          "MANAGEMENT_CONSOLE_GROUPS_ENABLED": true,
          "sfdc": true,
          "enableCsrf": true,
          "apiClientsEnabled": true
        },
        "tenantFeatures": {},
        "userFeatures": {}
      }