#This setting enables dev mode to include a local MongoDB install
devMode:
  enabled: true

#This setting accepts the EULA for the product
engine:
  acceptEULA: "yes"

identity-providers:
  secrets:
    idpConfigs:
      - discoveryUrl: "https://<TENANT>.auth0.com/.well-known/openid-configuration"
        primary: true
        clientId: "<CLIENT_ID>"
        clientSecret: "<CLIENT_SEECRET>"
        realm: "Auth0"
        hostname: "<INGRESS_IP/HOSTNAME>"
        useClaimsFromIdToken: true
        # claimsMapping:
          # client_id: "user_id"
          # name: "name"

# We use a global persistence statement for maximum compatibility with future releases.  This will create multiple PVCs.
global:
  persistence:
    storageClass: "nfs-dynamic"
