#This setting enables dev mode to include a local MongoDB install
devMode:
  enabled: true

#This setting accepts the EULA for the product
engine:
  acceptEULA: "yes"

identity-providers:           
  secrets:
    idpConfigs:
      - discoveryUrl: "https://<TENANT>.auth0.com/.well-known/openid-configuration"
        primary: true
        clientId: "<CLIENT_ID>"
        clientSecret: "<CLIENT_SEECRET>"
        realm: "Auth0"
        hostname: "<INGRESS_IP/HOSTNAME>"
        claimsMapping:
          client_id: [ "client_id", "azp" ]
          groups: "/https:~1~1qlik.com~1groups"
          sub: ["/https:~1~1qlik.com~1sub", "sub"]
global:
  persistence:
    storageClass: "nfs-dynamic"