#This setting enables dev mode to include a local MongoDB install
devMode:
  enabled: true

#This setting accepts the EULA for the product
engine:
  acceptEULA: "yes"

identity-providers:           
  secrets:
    idpConfigs:
      - discoveryUrl: "https://<TENANT>.auth0.com/.well-known/openid-configuration"
        primary: true
        clientId: "<CLIENT_ID>"
        clientSecret: "<CLIENT_SEECRET>"
        realm: "Auth0"
        hostname: "<INGRESS_IP/HOSTNAME>"
        claimsMapping:
          client_id: [ "client_id", "azp" ]
          groups: "/https:~1~1qlik.com~1groups"
          sub: ["/https:~1~1qlik.com~1sub", "sub"]
global:
  persistence:
    storageClass: "nfs-dynamic"
qix-datafiles:
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
redis:
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
reporting:
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
resource-library:
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
temporary-contents:
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
engine:
  acceptEULA: "yes"
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: qseok-vol
dcaas:
  dcaas-redis:
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      existingClaim: qseok-vol